// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7MYZWkVYhkdNyxTyBz2XqxKEcSZstGc',
    appId: '1:792311920930:web:a31c1fc236c99344954d7b',
    messagingSenderId: '792311920930',
    projectId: 'helloworld-68ae3',
    authDomain: 'helloworld-68ae3.firebaseapp.com',
    databaseURL: 'https://helloworld-68ae3-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-68ae3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBHeV0nYRnDS3iDN_FtFQwfbHYB_j3sEY',
    appId: '1:792311920930:android:e85bcfa1eb44ce5b954d7b',
    messagingSenderId: '792311920930',
    projectId: 'helloworld-68ae3',
    databaseURL: 'https://helloworld-68ae3-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-68ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBld-BFf6Kyk8b-EVGm6FkPwzpIlrIIyTk',
    appId: '1:792311920930:ios:04adb335da50a4b4954d7b',
    messagingSenderId: '792311920930',
    projectId: 'helloworld-68ae3',
    databaseURL: 'https://helloworld-68ae3-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-68ae3.appspot.com',
    iosClientId: '792311920930-qb6fl9cfkktd0p02v3j8o96n1o2fni5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloOk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBld-BFf6Kyk8b-EVGm6FkPwzpIlrIIyTk',
    appId: '1:792311920930:ios:04adb335da50a4b4954d7b',
    messagingSenderId: '792311920930',
    projectId: 'helloworld-68ae3',
    databaseURL: 'https://helloworld-68ae3-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-68ae3.appspot.com',
    iosClientId: '792311920930-qb6fl9cfkktd0p02v3j8o96n1o2fni5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloOk',
  );
}
